config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ] # When did this format change? from [:index] to %i [index]?

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-background-grey-lighter">
  <head>
    <title>Carbon Reddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;900&display=swap" rel="stylesheet">
  </head>

  <body data-controller="navbar-toggle">
    <%= render partial: "shared/navbar" %>
    <div class="container is-max-widescreen">
      <div class="container is-fluid">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %>prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label"%>
    <div class="control">
      <%= form.text_field :title, class:"input", placeholder:"Text input"%>
    </div>
  </div>

  <div class="field">
    <%= form.label :url, class: "label"%>
    <div class="control">
      <%= form.text_field :url, class:"input is-link", placeholder:"Text input"%>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.submit class:"button is-link"%>
    </div>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <p>
    <strong>Title:</strong>
    <%= link.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= link.url %>
  </p>

</div>

app/views/links/edit.html.erb
<div class="content">
  <p></p>
  <div class="box">
    <h1>Editing Link</h1>
    <%= render "form", link: @link %>
    <p></p>
      <%= link_to "Back to links", links_path, class: "button"%>
  </div>
</div>

app/views/links/index.html.erb
<div class="content">
  <p style="color: green"><%= notice %></p>

  <% @links.each do |link| %>
    <div class="box">
      <p class="title"><%= link_to link.title, link %></p>
      <p class="subtitle">Submitted <%= time_ago_in_words(link.created_at) %>
      by <%= link.user.email %></p>
    </div>
  <% end %>

</div>

app/views/links/new.html.erb
<div class="content">
  <p></p>
  <div class="box">
    <h1>New Link</h1>
    <%= render "form", link: @link %>
    <p></p>
    <%= link_to "Back to links", links_path, class:"button" %>
  </div>
</div>

app/views/links/show.html.erb
<div class="content">
  <p style="color: green"><%= notice %></p>
  <div class="box">
    <p class="title" href="<%= @link.url %>"><%= @link.title %></p>
    <p class="subtitle">Submitted by <%= @link.user.email %></p>

    <div class="field is-grouped buttons are-small">
      <div class="control"><%= link_to "Visit", @link.url, class: "button is-link" %></div>
      <% if @link.user == current_user %>
        <div class="control"><%= link_to "Edit", edit_link_path(@link), class: "button" %></div>
        <div class="control"><%= button_to "Delete", @link, method: :delete, class: "button is-danger" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="<%= root_path %>" >
      <%= image_tag("carbon_reddit.png") %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
        <% if user_signed_in? -%>
          <a class="button is-dark" href="<%= new_link_path %>" >
            <strong>Submit Link</strong>
          </a>
          <a class="button is-light" href="<%= edit_user_registration_path %>">
            Account
          </a>
          <a class="button is-light" href="<%= destroy_user_session_path %>">
            Sign Out
          </a>
        <% else -%>
          <a class="button is-primary" href="<%= new_user_registration_path %>" >
            <strong>Sign Up</strong>
          </a>
          <a class="button is-light" href="<%= new_user_session_path %>">
            Log In
          </a>
        <% end -%>
        </div>
      </div>
    </div>
  </div>
</nav>